run:
  timeout: 5m
  go: "1.24"

linters-settings:
  gocritic:
    enabled-tags:
    - performance
  lll:
    line-length: 200
  misspell:
    locale: US
  revive:
    rules:
    - name: dot-imports
      arguments:
        # dot import should be ONLY allowed for ginkgo testing packages
        - allowedPackages:
          - "github.com/onsi/gomega"

linters:
  disable-all: true
  enable:
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - gosec
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unused
    - whitespace
  # Run with --fast=false for more extensive checks (enables all linters)
  fast: true

issues:
  # default: 50
  max-issues-per-linter: 0
  exclude-rules:
    - text: "unused-parameter: parameter '.*' seems to be unused, consider removing or renaming it as _"
      linters:
        - revive
  exclude-files:
    - "zz_generated.*\\.go$"
    - "pkg/util/fileutil/atomic_writer.go"
    - "pkg/util/fileutil/atomic_writer_test.go"

  # default: 3
  max-same-issues: 0

severity:
  # default: ''
  default-severity: error
