codecov:
  notify:
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      default:
        threshold: 5%
        target: auto
        base: auto
    patch:
      default:
        threshold: 5%
        target: auto
        base: auto
        branches:
        - master

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  branches:
    - master

ignore:
  - "test/**/*.go"
