apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: secrets-store.csi.k8s.io
spec:
  podInfoOnMount: true
  attachRequired: false
  volumeLifecycleModes:
  - Ephemeral
  requiresRepublish: true # added in Kubernetes 1.20, this field is beta as of Kubernetes 1.21
